language: android
android:
  componenets:
    - tools
    - platform-tools

    script:
      - ./gradlew assembleDebug
      - ./scripts/upload-app.sh
      - ./gradlew testDebug --tests=tests.TestRunner
      - ./gradlew clean
      - ./scripts/merge.sh