language: android
android:
before_install:
  - chomd -R +x ./scripts

  componenets:
    - tools
    - build-tools-26.0.2
    - android-26

licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
  - ./gradlew assembleDebug
  - ./scripts/upload-app.sh
  - ./gradlew testDebug --tests=tests.TestRunner
  - ./gradlew clean
  - ./scripts/merge.sh